# Build, Tag & Push a new prerelease to dockerhub off of a tag

name: Docker Pre-release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+_[0-9]+-rc.[0-9]+'


jobs:
  docker_prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: nelonoel/branch-name@v1.0.1

      - name: Docker Login
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"

      - name: Create Version
        id: version
        if: success()
        run: |
          # TODO: find a better way to version from tags
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # set to output var
          echo ::set-output name=VERSION::${VERSION}

      - name: Build and Tag
        if: success()
        env:
          VERSION: ${{ steps.version.outputs.VERSION }}
        run: make build
      
      - name: Push
        if: success()
        env:
          VERSION: ${{ steps.version.outputs.VERSION }}
        run: make push
